#cloud-config

timezone: Asia/Tokyo
locale: ja_JP.utf8

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL

runcmd:
  - sudo apt upgrade && sudo apt update
  - sudo apt -y install nano curl jq build-essential
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
